### ISSUE TITLE
Duplicate Excel 2010 Function

### ISSUE THREAD

**Issue by joeyiii57** [ClimberMel/SMF_Add-in#18]
There is a routine in the smfUtilities_ module name IfError.  There is a built-in Excel 2010 function with the same name.

**Comment by ClimberMel** [comment]
There are no calls to it from any module.  I am going to guess it was a formula that Randy used for something.  He had a few routines that were for his testing and also fo older versions of Excel.  You can't call it in Excel 2010.  I changed the name slightly so that I could call it and it returned 0 for a division be zero error but didn't display the error message.

**Comment by joeyiii57** [comment]
The only reason I noticed it was because I was writing a rather large formula in an excel workbook and kept getting a VBA error but I wasnt actually using any macros.  Changed the name and VBA error stopped popping up.  I looked for use in other macros and couldn't find any either.  Thanks.
iii
