### ISSUE TITLE
smfStrExtr() function documentation

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#38]
Hi Mel,

attached is an html file containing the documentation for =smfStrExt().  I wrote the doc in MS Word and saved it as HTML.  I can't vouch for Word's conversion to html but it looks like it will work.  Let me know if creating missing documentation using this process works and I'll work on some more. 

[smfStrExtr() - doc.zip](https://github.com/ClimberMel/SMF_Add-in/files/11644504/smfStrExtr.-.doc.zip)

Regards,
~ Bruce

**Comment by ClimberMel** [comment]
Thanks, Bruce, I saved this in /Doc-links/smfStrExtr-function_files/ as smfStrExtr-function.htm and called it using my template for documentation. It works well although I need to remove a lot of the MS-Word inserted code. I am putting it here as a reminder that it could use clean up to make it consistent to the other document modules.

**Comment by ClimberMel** [comment]
The Documentation files have a calling html file that has a standard navigation header and an iframe to display the content saved in a folder.
The structure is for the calling html: smfStrExtr-function.htm
Then the folder is the same with files appended: smfStrExtr-function_files
The the actual content is the same as the calling html but with just htm as a suffix: smfStrExtr-function.htm

**Comment by Bruce-95** [comment]
Hi Mel,

Since I don't know anything about coding html/web pages, what you're saying above is like my dog hearing "blah, blah, blah, Bad Dog, blah, blah, Bad Dog...".   :-)

Yeah I figured Word's conversion to HTML created a lot of bloated code.

Do you want me to provide any missing/updated doc files in the future?  If so, what format is best - txt, pdf, doc, docx, etc?   And what's the best way to send them to you - GitHub or maybe https://groups.google.com/g/SMF-addin  keeping in mind my limited knowledge of GitHub right now?

~ Bruce

**Comment by ClimberMel** [comment]
This was fine.  It still easier for me to clean it up than to create it from scratch.GitHub is best as it works as a to do list for me and I can add notes and such as I did with this one.  No worries about the meaningless babble... that is mainly for me or in case someone else comes along and looks at these.  :)Thanks,MelSent from my Galaxy
-------- Original message --------From: Bruce-95 ***@***.***> Date: 2023-06-04  4:24 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: ClimberMel ***@***.***>, Assign ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] smfStrExtr() function documentation (Issue #38) 
Hi Mel,
Since I don't know anything about coding html/web pages, what you're saying above is like my dog hearing "blah, blah, blah, Bad Dog, blah, blah, Bad Dog...".   :-)
Yeah I figured Word's conversion to HTML created a lot of bloated code.
Do you want me to provide any missing/updated doc files in the future?  If so, what format is best - txt, pdf, doc, docx, etc?   And what's the best way to send them to you - GitHub or maybe https://groups.google.com/g/SMF-addin  keeping in mind my limited knowledge of GitHub right now?
~ Bruce
