### ISSUE TITLE
=smfGetEconData() returning "Error"

### ISSUE THREAD

**Issue by Bruce-95** [ClimberMel/SMF_Add-in#73]
A [user reported ](https://groups.google.com/g/smf-addin/c/LxVZsoALqe4/m/_GqSfF69AAAJ)the function is now returning "Error" on all invocations. Also there is no documentation for =smfGetEconData() on SMF's  web site.

**Comment by Bruce-95** [comment]
Mel,
well I just did my first fork/pull request. Do you have any naming standards you want to use for forks and pull requests? Like putting the issue # in?

~ Bruce S

**Comment by ClimberMel** [comment]
Probably best is to use Issue #.  I'd normally use version, but since the SMF uses a date for version that would be hard to do.MelSent from my Galaxy
-------- Original message --------From: Bruce S ***@***.***> Date: 2024-07-03  5:31 p.m.  (GMT-08:00) To: ClimberMel/SMF_Add-in ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [ClimberMel/SMF_Add-in] =smfGetEconData() returning "Error" (Issue #73) 
Mel,
well I just did my first fork/pull request. Do you have any naming standards you want to use for forks and pull requests? Like putting the issue # in?
~ Bruce S
